language: php

sudo: false

# Test main supported versions of PHP against latest WP.
php:
  - 7.1

env:
  - WP_VERSION=latest WP_MULTISITE=0 PHP_LATEST_STABLE=7.1

before_script:
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - bash tests/bin/install.sh dlm_test root '' localhost $WP_VERSION
  - bash tests/bin/travis.sh before

script:
  - bash tests/bin/phpunit.sh

after_script:
  - bash tests/bin/travis.sh after